api_platform:
    formats: 
        json: ['application/json']
        jsonld: ['application/ld+json']
        html: ['text/html']
        multipart: ['multipart/form-data']
    swagger:
        api_keys: # En essaie ici de remplire qlchs dans le bouton 'Authorize' (ApiPlatform)
            cookieAuth: # je sais pas si c'est approprié mais voir OpenApiFactory pour voir comment faire dans version antérieur api-platform ($schemas['cookieAuth'])  
                name: PHPSESSID
                type: header